# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dbc80b0b42941f134eba21680ad8a00ca965169a1cffcb8c1b54c675c04c577608ed01e5a5e73310936d16cc27980b75a972d94818f7ae6fc9e5d02ddc77e02

test:
  secret_key_base: c4acd41223627a3c1b66818e79af0f7673ea11a19aad57d96025cfc4bb4ce89de7bb96bcd245d8ad3d3181d6bb4cceec7167a1980cb7ad4ad7cc6610f1781c4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
